### ISSUE TITLE
Issue with MongoDB sink connector when trying to CDC from debezium SQL server 0.9.5 driver

### ISSUE THREAD

**Issue by bugf1nd3r** [hpgrahsl/kafka-connect-mongodb#82]
Hi,

I am using confluent kafka to capture change data from SQL server (source) to MongoDB (sink).

I am using ```debezium/debezium-connector-sqlserver:0.9.5``` for SQl server and below is the configuration of SQL server driver

```
{
 "name": "test1",
 "config": {
   "connector.class": "io.debezium.connector.sqlserver.SqlServerConnector",
   "database.hostname": "x.x.x.x",
   "database.port": "1433",
   "database.user": "user",
   "database.password": "pass",
   "database.dbname": "db_name",
   "database.server.name": "servername",
   "table.whitelist": "dbo.customer_detail",
   "database.history.kafka.bootstrap.servers": "localhost:9092",
   "database.history.kafka.topic": "customer_detail"
 }
}
```

When I register this source driver, I am able to consume messages for the topic ```servername.dbo.customer_detail``` using avro console consumer.

In order to sink this data in MongoDB, I am using ```hpgrahsl/kafka-connect-mongodb:1.3.1 ``` version. below is configuration of sink connector

```
{
  "name": "mdb-sink-debezium-cdc",
  "config": {
    "key.converter":"io.confluent.connect.avro.AvroConverter",
    "key.converter.schema.registry.url":"http://localhost:8081",
    "value.converter":"io.confluent.connect.avro.AvroConverter",
    "value.converter.schema.registry.url":"http://localhost:8081",
    "connector.class": "at.grahsl.kafka.connect.mongodb.MongoDbSinkConnector",
    "topics": "myreplset.kafkaconnect.mongosrc",
    "mongodb.connection.uri": "mongodb://kafka:kafka01@dbhost.com:27017/Test",
    "mongodb.change.data.capture.handler": "at.grahsl.kafka.connect.mongodb.cdc.debezium.mongodb.MongoDbHandler",
    "mongodb.collection": "mongosink"
  }
}
```

Now I have created *Test* database and *mongosink* collection inside it. When I register this driver to connect.. after lots of logs I see one error in logs :

```
ERROR WorkerSinkTask{id=mdb-sink-debezium-cdc-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:177)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:560)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:321)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.DataException: org.bson.BsonInvalidOperationException: Value expected to be of type STRING is of unexpected type DOCUMENT
	at at.grahsl.kafka.connect.mongodb.cdc.debezium.mongodb.MongoDbInsert.perform(MongoDbInsert.java:53)
	at at.grahsl.kafka.connect.mongodb.cdc.debezium.mongodb.MongoDbHandler.handle(MongoDbHandler.java:75)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at at.grahsl.kafka.connect.mongodb.MongoDbSinkTask.buildWriteModelCDC(MongoDbSinkTask.java:247)
	at at.grahsl.kafka.connect.mongodb.MongoDbSinkTask.processSinkRecords(MongoDbSinkTask.java:142)
	at at.grahsl.kafka.connect.mongodb.MongoDbSinkTask.lambda$null$0(MongoDbSinkTask.java:118)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at at.grahsl.kafka.connect.mongodb.MongoDbSinkTask.lambda$put$1(MongoDbSinkTask.java:117)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at at.grahsl.kafka.connect.mongodb.MongoDbSinkTask.put(MongoDbSinkTask.java:112)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:538)
	... 10 more
Caused by: org.bson.BsonInvalidOperationException: Value expected to be of type STRING is of unexpected type DOCUMENT
	at org.bson.BsonValue.throwIfInvalidType(BsonValue.java:419)
	at org.bson.BsonValue.asString(BsonValue.java:69)
	at at.grahsl.kafka.connect.mongodb.cdc.debezium.mongodb.MongoDbInsert.perform(MongoDbInsert.java:44)
	... 27 more
[2019-05-17 16:33:55,878] ERROR WorkerSinkTask{id=mdb-sink-debezium-cdc-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:178)
```

Is this error the reason why I am not seeing any data in MongoDB?

**Comment by hpgrahsl** [comment]
1) YES in case a sink connector's log shows ```Task is being killed and will not recover until manually restarted``` it means no further processing will be done from this SinkTask. So this is the reason why you don't see data arriving in your MongoDB collection.

2) Based on your description I assume you are using the wrong CDC handler. If you use Debezium Mysql Connector you are supposed to make use of the **MysqlHandler** for the Sink Connector as well :)

```properties
mongodb.change.data.capture.handler=at.grahsl.kafka.connect.mongodb.cdc.debezium.rdbms.mysql.MysqlHandler
```
Doing so should most likely solve your problem above. Let me know if it works with this configuration change.

**Comment by bugf1nd3r** [comment]
Hi,

I am not using Debezium Mysql Connector. I am using Debezium SQL Server connector as source.

here is driver link : https://www.confluent.io/connector/debezium-sql-server-cdc-connector/

**Comment by hpgrahsl** [comment]
@bugf1nd3r sorry I misread this obviously. but still you need to use a compatible CDC handler according to the source. A while back I successfully tested (manually) the compatibility of my implementation (see **RdbmsHandler**) with the SQL server source connector of Debezium. So give it a spin with the following, and in case they didn't introduce any breaking changes since I last tried it you might be sucessful:

```properties
mongodb.change.data.capture.handler=at.grahsl.kafka.connect.mongodb.cdc.debezium.rdbms.RdbmsHandler
```

In fact the _RdbmsHandler_ and _MysqlHandler_ of the sink connector are currently equivalent :)

**Comment by bugf1nd3r** [comment]
Thanks @hpgrahsl for correct cdc handler.

Now when I register sink driver, I don't get `null` exception. I am getting connected message

```[2019-05-28 11:57:12,079] INFO Monitor thread successfully connected to server with description ServerDescription{address=mongoserver:27017, type=REPLICA_SET_PRIMARY, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 6, 2]}, minWireVersion=0, maxWireVersion=6, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=296688320, setName='rs0', canonicalAddress=houoradb2.oii.oceaneering.com:27017, hosts=[mongoserver:27017], passives=[], arbiters=[], primary='mongoserver:27017', tagSet=TagSet{[]}, electionId=7fffffff0000000000000008, setVersion=1, lastWriteDate=Tue May 28 11:57:07 IST 2019, lastUpdateTimeNanos=4654515696390} (org.mongodb.driver.cluster:71)```

But problem is when I try to update record from SQL server, I can see null exception in connect logs .

Here is message I am getting in connect logs when I try to update data in source (SQL Server)

```
[2019-05-28 11:59:38,240] ERROR WorkerSinkTask{id=mdb-sink-debezium-cdc-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask:558)
java.lang.NullPointerException
	at at.grahsl.kafka.connect.mongodb.MongoDbSinkTask.buildWriteModelCDC(MongoDbSinkTask.java:245)
	at at.grahsl.kafka.connect.mongodb.MongoDbSinkTask.processSinkRecords(MongoDbSinkTask.java:142)
	at at.grahsl.kafka.connect.mongodb.MongoDbSinkTask.lambda$null$0(MongoDbSinkTask.java:118)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at at.grahsl.kafka.connect.mongodb.MongoDbSinkTask.lambda$put$1(MongoDbSinkTask.java:117)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at at.grahsl.kafka.connect.mongodb.MongoDbSinkTask.put(MongoDbSinkTask.java:112)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:538)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:321)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2019-05-28 11:59:38,241] ERROR WorkerSinkTask{id=mdb-sink-debezium-cdc-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:177)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:560)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:321)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at at.grahsl.kafka.connect.mongodb.MongoDbSinkTask.buildWriteModelCDC(MongoDbSinkTask.java:245)
	at at.grahsl.kafka.connect.mongodb.MongoDbSinkTask.processSinkRecords(MongoDbSinkTask.java:142)
	at at.grahsl.kafka.connect.mongodb.MongoDbSinkTask.lambda$null$0(MongoDbSinkTask.java:118)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at at.grahsl.kafka.connect.mongodb.MongoDbSinkTask.lambda$put$1(MongoDbSinkTask.java:117)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at at.grahsl.kafka.connect.mongodb.MongoDbSinkTask.put(MongoDbSinkTask.java:112)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:538)
	... 10 more
[2019-05-28 11:59:38,241] ERROR WorkerSinkTask{id=mdb-sink-debezium-cdc-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:178)
[2019-05-28 11:59:38,241] INFO stopping MongoDB sink task (at.grahsl.kafka.connect.mongodb.MongoDbSinkTask:258)
[2019-05-28 11:59:38,242] INFO [Consumer clientId=consumer-11, groupId=connect-mdb-sink-debezium-cdc] Member consumer-11-acae4f4a-24f5-445e-b65f-72cd6e4042eb sending LeaveGroup request to coordinator kali.example.com:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:822)
```

My MongoDB sink config is as below

```
{
  "name": "mdb-sink-debezium-cdc",
  "config": {
    "key.converter":"io.confluent.connect.avro.AvroConverter",
    "key.converter.schema.registry.url":"http://localhost:8081",
    "value.converter":"io.confluent.connect.avro.AvroConverter",
    "value.converter.schema.registry.url":"http://localhost:8081",
    "connector.class": "at.grahsl.kafka.connect.mongodb.MongoDbSinkConnector",
    "topics": "server.dbo.newtable1",
    "mongodb.connection.uri": "mongodb://kafka:kafka01@mongoserver:27017/Test",
    "mongodb.change.data.capture.handler": "at.grahsl.kafka.connect.mongodb.cdc.debezium.rdbms.RdbmsHandler",
    "mongodb.collection": "mongosink"
  }
}
```

**Comment by hpgrahsl** [comment]
@bugf1nd3r Thx for getting back again. It looks like you found a bug - congratulations :) Since it shouldn't be hard to fix I try to provide a fix soonish.

Until then you might try to workaround with the following configuration change:

```json
{ 
...
"mongodb.collections":"mongosink",
"mongodb.collection.server.dbo.newtable1":"mongosink",
"mongodb.change.data.capture.handler.mongosink":"at.grahsl.kafka.connect.mongodb.cdc.debezium.rdbms.RdbmsHandler"
}
```
Ideally you won't run into the NPE with this anymore.

**Comment by bugf1nd3r** [comment]
Thank you @hpgrahsl for workaround. I am now able to live sync data SQL server 2017 to MongoDB. 
Thanks for creating this awesome driver. :)

Eagerly waiting for future updates.

**Comment by IqraSami** [comment]
@hpgrahsl hey! I am facing the same error while connecting Kafka with MongoDB

This is my Mongo Sink Connector:
```

name=mongo-sink
topics=connect-test
connector.class=com.mongodb.kafka.connect.MongoSinkConnector
tasks.max=15
key.ignore=true
connection.uri=mongodb://localhost:27017
database=ac******
collection=hp
max.num.retries=30
retries.defer.timeout=5000
type.name=kafka-connect
schemas.enable=false

```
and the Error which this is throwing now is:

```
[2021-09-16 10:34:20,838] ERROR WorkerSinkTask{id=mongo-sink-9} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:191)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
    at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:614)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:329)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:232)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:201)
    at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:189)
    at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:238)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.kafka.connect.errors.DataException: Unexpected data conversion exception.
    at com.mongodb.kafka.connect.sink.converter.LazyBsonDocument.getUnwrapped(LazyBsonDocument.java:133)
    at com.mongodb.kafka.connect.sink.converter.LazyBsonDocument.containsKey(LazyBsonDocument.java:60)
    at com.mongodb.kafka.connect.sink.processor.DocumentIdAdder.shouldAppend(DocumentIdAdder.java:60)
    at com.mongodb.kafka.connect.sink.processor.DocumentIdAdder.lambda$process$0(DocumentIdAdder.java:48)
    at java.base/java.util.Optional.ifPresent(Optional.java:183)
    at com.mongodb.kafka.connect.sink.processor.DocumentIdAdder.process(DocumentIdAdder.java:46)
    at com.mongodb.kafka.connect.sink.MongoSinkTask.lambda$buildWriteModel$5(MongoSinkTask.java:277)
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
    at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)
    at com.mongodb.kafka.connect.sink.MongoSinkTask.lambda$buildWriteModel$6(MongoSinkTask.java:277)
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
    at com.mongodb.kafka.connect.sink.MongoSinkTask.buildWriteModel(MongoSinkTask.java:274)
    at com.mongodb.kafka.connect.sink.MongoSinkTask.processSinkRecords(MongoSinkTask.java:194)
    at com.mongodb.kafka.connect.sink.MongoSinkTask.lambda$put$2(MongoSinkTask.java:134)
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
    at com.mongodb.kafka.connect.sink.MongoSinkTask.lambda$put$3(MongoSinkTask.java:132)
    at java.base/java.util.HashMap.forEach(HashMap.java:1336)
    at com.mongodb.kafka.connect.sink.MongoSinkTask.put(MongoSinkTask.java:127)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:586)
    ... 10 more
Caused by: org.apache.kafka.connect.errors.DataException: Error: no converter present due to unexpected object type java.lang.Double
    at com.mongodb.kafka.connect.sink.converter.SinkConverter.getRecordConverter(SinkConverter.java:83)
    at com.mongodb.kafka.connect.sink.converter.SinkConverter.lambda$convert$1(SinkConverter.java:56)
    at com.mongodb.kafka.connect.sink.converter.LazyBsonDocument.getUnwrapped(LazyBsonDocument.java:131)
    ... 28 more
[2021-09-16 10:34:20,838] INFO Stopping MongoDB sink task (com.mongodb.kafka.connect.sink.MongoSinkTask:175)
```

Perviously it was working, but now it has been stopped and not working. Can you explain what are causing this error and how can I remove this?
